### ISSUE TITLE
[feat] Category Color Model 생성 및 Category API 코드 작성

### ISSUE THREAD

**Issue by snowedev** [teamCA-PIN/CA-PIN_Server#13]
## 💡 제목
Category API 코드 작성

## 🚀 작업 브랜치
`feature/#13`

## 📝 todo
- [x] 카테고리 컬러별 모델 생성
- [x] 새로운 카테고리 추가
- [x] 회원가입시 기본 카테고리 자동 생성
- [x] 카테고리에 핀 등록
- [x] 카테고리 삭제
- [x] 내 카테고리 목록 모아보기
- [x] 카테고리에 포함된 카페 리스트 조회
