### ISSUE TITLE
[bug] 1차 배포 전 버그 점검 및 response message 수정

### ISSUE THREAD

**Issue by snowedev** [teamCA-PIN/CA-PIN_Server#32]
## 개요
- 1차 배포 전 버그 점검 및 response message 수정이 필요합니다.
 
### 🐞 버그 설명(발생 환경)
- 버그는 없었습니다 코드 전반적으로 다듬으려고 합니다.

### 📝 todo
- [x] cafetiService.ts의 cafeti 부분 deprecated된 속성에 따라 추가 코드 작성
- [x] 유저 정보 조회시 프로필 이미지없는 경우 처리(cafeti 이미지로 필드 업데이트)
- [x] cafetiService.ts의 cafeti case문 default 처리
- [x] 에러 코드 및 에러 메시지 수정
- [x] api 응답 보낼 시 return 추가 및 필요없는 파일 삭제
