### ISSUE TITLE
[feat] 프로필 편집 API, 닉네임 조건 검사, CAFETI 모델 변경

### ISSUE THREAD

**Issue by snowedev** [teamCA-PIN/CA-PIN_Server#60]
## 💡 제목
- 프로필 편집 API 신규 개발
- 닉네임 조건 검사
- CAFETI 모델 변경

## 🚀 작업 브랜치
`feature/#60`

## 📝 todo
- [x] 프로필 편집 API Service
- [x] 프로필 편집 API Controller
- [x] 닉네임 조건 검사(2~10글자, 특문 제한)
- [x] CAFETI에 프로필용 이미지 필드 추가
