### ISSUE TITLE
[feat] Category 색상 변경, CAFETI 소개 데이터 추가 반영

### ISSUE THREAD

**Issue by snowedev** [teamCA-PIN/CA-PIN_Server#85]
## 💡 제목
변경된 데이터 반영

## 🚀 작업 브랜치
`feat/#85`

## 📝 todo
- [x] Category 색상 값 변경 - DB
- [x] Cafeti 캐릭터별 소개 추가 - DB
- [x] CAFETI Interface 변경
- [x] CAFETI API ResponseData 변경
